import json
import urllib.request
from typing import Dict, Any

class OllamaResource:
    """Authentic reasoning resource connecting directly to a local Ollama instance."""
    
    def __init__(self, model_name: str = "llama3.1:latest", url: str = "http://localhost:11434/api/generate"):
        self.model = model_name
        self.url = url
        
    def generate(self, prompt: str, schema: Any = None) -> Dict[str, Any]:
        """Queries local Ollama passing the strict schema rules generated by ReasonSpec natively."""
        
        # We enforce JSON output generation inherently
        payload = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,
            "format": "json"
        }
        
        req = urllib.request.Request(
            self.url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"}
        )
        
        print(f"\\n[Reasoning] Querying Local Ollama ({self.model})...")
        try:
            with urllib.request.urlopen(req) as response:
                result_bytes = response.read()
                result_json = json.loads(result_bytes)
                
                # Extract the message payload cleanly
                output_text = result_json.get("response", "")
                
                # Strict JSON cast mirroring schema parsing
                parsed_dstt = json.loads(output_text)
                return parsed_dstt
                
        except Exception as e:
            print(f"[Error] Failed communicating with local LLM. Did it return valid JSON? {e}")
            raise e
